CREATE TABLE Person (
	person_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE Car (
	car_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	model VARCHAR(50),
	owner_id INTEGER NOT NULL,
	FOREIGN KEY (owner_id) REFERENCES Person (person_id)
);

CREATE TABLE Part_type (
	part_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	part_name VARCHAR(50) NOT NULL
);

CREATE TABLE Part (
	part_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	car_id INTEGER NOT NULL,
	part_type_id INTEGER NOT NULL,
	FOREIGN KEY (car_id) REFERENCES Car (car_id),
	FOREIGN KEY (part_type_id) REFERENCES Part_type (part_type_id)
);

CREATE TABLE Action_type (
	action_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	description TEXT NOT NULL
);

CREATE TABLE Action (
	action_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	person_id INTEGER NOT NULL,
	part_id INTEGER NOT NULL,
	action_type_id INTEGER NOT NULL,
	FOREIGN KEY (person_id) REFERENCES Person (person_id),
	FOREIGN KEY (part_id) REFERENCES Part (part_id),
	FOREIGN KEY (action_type_id) REFERENCES Action_type (action_type_id)
);


CREATE TABLE Car_status (
	car_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	status TEXT NOT NULL
);

insert into Person (name) values ('Тим');

insert into Car (owner_id) values (1);

insert into Car_status (status) values ('стоит на месте'), ('сполз чуть вниз');

insert into Part_type (part_name) values ('руль'), ('стекло боковой двери'),('пол салона');

insert into Part (car_id, part_type_id) values (1, 1), (1, 2), (1, 3);

insert into Action_type (description) values ('оперся'), ('выглянул еще дальше'), ('посмотрел на землю'), ('встал на цыпочки');

insert into Action (person_id, part_id, action_type_id) values (1, 1, 1), (1, 2, 2), (1, 2, 3), (1, 3, 4);

-- select *
-- from Car
-- inner join Person on Car.owner_id = Person.person_id;

-- select * 
-- from Part
-- inner join Part_type on Part.part_type_id = Part_type.part_type_id;

-- select *
-- from Action
-- inner join Person on Action.person_id = Person.person_id
-- inner join Part on Action.part_id = Part.part_id
-- inner join Action_type on Action.action_type_id = Action_type.action_type_id;
